# Generated by Django 4.2.5 on 2024-01-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioActivity', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
