# Generated by Django 4.2.5 on 2024-01-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioActivity', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmilesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.CharField(max_length=256)),
                ('pic50', models.IntegerField(max_length=256)),
            ],
        ),
    ]
