# Generated by Django 4.2.5 on 2024-01-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioActivity', '0004_smilesdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
