# Generated by Django 5.0.1 on 2024-01-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioActivity', '0005_delete_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='smilesdata',
            name='bio_class',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='smilesdata',
            name='pic50',
            field=models.IntegerField(),
        ),
    ]
