# Generated by Django 5.0.1 on 2024-01-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioActivity', '0007_alter_smilesdata_pic50'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smilesdata',
            name='smiles',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
