# Generated by Django 5.0.1 on 2024-01-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioActivity', '0008_alter_smilesdata_smiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempSmilesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.CharField(max_length=256, unique=True)),
                ('pic50', models.FloatField()),
                ('bio_class', models.BooleanField(default=False)),
            ],
        ),
    ]
