# Generated by Django 5.0.1 on 2024-01-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioActivity', '0009_tempsmilesdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempSmilesData',
            new_name='CurrSmilesData',
        ),
    ]
