# Generated by Django 5.0.1 on 2024-01-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioActivity', '0010_rename_tempsmilesdata_currsmilesdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currsmilesdata',
            name='bio_class',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='smilesdata',
            name='bio_class',
            field=models.IntegerField(),
        ),
    ]
