# Generated by Django 5.0.1 on 2024-01-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioActivity', '0012_alter_currsmilesdata_bio_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currsmilesdata',
            name='pdb_file',
            field=models.FileField(blank=True, null=True, upload_to='molecules/current/'),
        ),
        migrations.AddField(
            model_name='smilesdata',
            name='pdb_file',
            field=models.FileField(blank=True, null=True, upload_to='molecules/all/'),
        ),
    ]
